#!/bin/bash

which cmake > /dev/null || sudo apt install cmake
CURR_PWD=$(pwd)
CMAKE_SDL_SETTINGS=(
    -DCMAKE_INSTALL_PREFIX=$HOME/.local
    -DSDL_VIDEO=ON
    -DSDL_VIDEO_DRIVER_X11=ON
    -DSDL_X11=ON
    -DSDL_WAYLAND=OFF
    -DSDL_DIRECTFB=OFF
    -DSDL_KMSDRM=OFF
)

error () {
	printf "%s\n" "$1"
	cd "$CURR_PWD"
	exit 1
}

compile () {
	# Clone
	[ -d "$1" ] || git clone "https://github.com/libsdl-org/$1.git" || error "can't clone $1"
	cd "$1" || error "can't cd into $1"
	mkdir -p build && cd build

	# CMake
	if [ "$1" = "SDL" ]; then
		cmake .. "${CMAKE_SDL_SETTINGS[@]}" || error "can't configure $1"
	else
		cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DSDL3_DIR=$HOME/.local/lib/cmake/SDL3 || error "can't configure $1"
	fi

	# Build & install
	make -j"$(nproc)" || make || error "can't compile $1"
	make install || error "can't install $1"
	cd "$CURR_PWD"
}

# Environment
export CMAKE_PREFIX_PATH=$HOME/.local
export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
export PATH=$HOME/.local/bin:$PATH

compile SDL
compile SDL_mixer
compile SDL_image
