LOCAL_SRC_FILES := \
    src/atomic/SDL_atomic.c \
    src/atomic/SDL_spinlock.c \
    src/audio/SDL_audio.c \
    src/audio/SDL_audiocvt.c \
    src/audio/SDL_audiodev.c \
    src/audio/SDL_audiotypecvt.c \
    src/audio/SDL_mixer.c \
    src/audio/SDL_wave.c \
    src/audio/aaudio/SDL_aaudio.c \
    src/audio/android/SDL_androidaudio.c \
    src/core/android/SDL_android.c \
    src/cpuinfo/SDL_cpuinfo.c \
    src/dynapi/SDL_dynapi.c \
    src/events/SDL_clipboardevents.c \
    src/events/SDL_displayevents.c \
    src/events/SDL_dropevents.c \
    src/events/SDL_events.c \
    src/events/SDL_gesture.c \
    src/events/SDL_keyboard.c \
    src/events/SDL_keysym_to_scancode.c \
    src/events/SDL_mouse.c \
    src/events/SDL_quit.c \
    src/events/SDL_scancode_tables.c \
    src/events/SDL_touch.c \
    src/events/SDL_windowevents.c \
    src/events/imKStoUCS.c \
    src/file/SDL_rwops.c \
    src/filesystem/android/SDL_sysfilesystem.c \
    src/haptic/SDL_haptic.c \
    src/haptic/android/SDL_syshaptic.c \
    src/hidapi/SDL_hidapi.c \
    src/hidapi/android/hid.cpp \
    src/joystick/SDL_gamecontroller.c \
    src/joystick/SDL_joystick.c \
    src/joystick/SDL_steam_virtual_gamepad.c \
    src/joystick/android/SDL_sysjoystick.c \
    src/joystick/controller_type.c \
    src/libm/e_atan2.c \
    src/libm/e_exp.c \
    src/libm/e_fmod.c \
    src/libm/e_log.c \
    src/libm/e_log10.c \
    src/libm/e_pow.c \
    src/libm/e_rem_pio2.c \
    src/libm/e_sqrt.c \
    src/libm/k_cos.c \
    src/libm/k_rem_pio2.c \
    src/libm/k_sin.c \
    src/libm/k_tan.c \
    src/libm/s_atan.c \
    src/libm/s_copysign.c \
    src/libm/s_cos.c \
    src/libm/s_fabs.c \
    src/libm/s_floor.c \
    src/libm/s_scalbn.c \
    src/libm/s_sin.c \
    src/libm/s_tan.c \
    src/locale/SDL_locale.c \
    src/locale/android/SDL_syslocale.c \
    src/main/android/SDL_android_main.c \
    src/misc/SDL_url.c \
    src/misc/android/SDL_sysurl.c \
    src/power/SDL_power.c \
    src/power/android/SDL_syspower.c \
    src/render/SDL_d3dmath.c \
    src/render/SDL_render.c \
    src/render/SDL_yuv_sw.c \
    src/sensor/SDL_sensor.c \
    src/sensor/android/SDL_androidsensor.c \
    src/stdlib/SDL_crc16.c \
    src/stdlib/SDL_crc32.c \
    src/stdlib/SDL_getenv.c \
    src/stdlib/SDL_iconv.c \
    src/stdlib/SDL_malloc.c \
    src/stdlib/SDL_mslibc.c \
    src/stdlib/SDL_qsort.c \
    src/stdlib/SDL_stdlib.c \
    src/stdlib/SDL_string.c \
    src/stdlib/SDL_strtokr.c \
    src/test/SDL_test_assert.c \
    src/test/SDL_test_common.c \
    src/test/SDL_test_compare.c \
    src/test/SDL_test_crc32.c \
    src/test/SDL_test_font.c \
    src/test/SDL_test_fuzzer.c \
    src/test/SDL_test_harness.c \
    src/test/SDL_test_imageBlit.c \
    src/test/SDL_test_imageBlitBlend.c \
    src/test/SDL_test_imageFace.c \
    src/test/SDL_test_imagePrimitives.c \
    src/test/SDL_test_imagePrimitivesBlend.c \
    src/test/SDL_test_log.c \
    src/test/SDL_test_md5.c \
    src/test/SDL_test_memory.c \
    src/test/SDL_test_random.c \
    src/thread/SDL_thread.c \
    src/thread/generic/SDL_syscond.c \
    src/thread/generic/SDL_sysmutex.c \
    src/thread/generic/SDL_syssem.c \
    src/thread/generic/SDL_systhread.c \
    src/thread/generic/SDL_systls.c \
    src/timer/SDL_timer.c \
    src/video/SDL_RLEaccel.c \
    src/video/SDL_blit.c \
    src/video/SDL_blit_0.c \
    src/video/SDL_blit_1.c \
    src/video/SDL_blit_A.c \
    src/video/SDL_blit_N.c \
    src/video/SDL_blit_auto.c \
    src/video/SDL_blit_copy.c \
    src/video/SDL_blit_slow.c \
    src/video/SDL_bmp.c \
    src/video/SDL_clipboard.c \
    src/video/SDL_egl.c \
    src/video/SDL_fillrect.c \
    src/video/SDL_pixels.c \
    src/video/SDL_rect.c \
    src/video/SDL_shape.c \
    src/video/SDL_stretch.c \
    src/video/SDL_surface.c \
    src/video/SDL_video.c \
    src/video/SDL_vulkan_utils.c \
    src/video/SDL_yuv.c \
    src/video/android/SDL_androidclipboard.c \
    src/video/android/SDL_androidevents.c \
    src/video/android/SDL_androidgl.c \
    src/video/android/SDL_androidkeyboard.c \
    src/video/android/SDL_androidmessagebox.c \
    src/video/android/SDL_androidmouse.c \
    src/video/android/SDL_androidtouch.c \
    src/video/android/SDL_androidvideo.c \
    src/video/android/SDL_androidvulkan.c \
    src/video/android/SDL_androidwindow.c
