CREATE DATABASE IF NOT EXISTS ${WP_DB};

CREATE USER IF NOT EXISTS '${WP_ADMIN}'@'%' IDENTIFIED BY '${WP_ADMIN_PWD}';
CREATE USER IF NOT EXISTS '${WP_USER}'@'%' IDENTIFIED BY '${WP_USER_PWD}';

GRANT ALL PRIVILEGES ON *.* TO '${WP_ADMIN}'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ${WP_DB}.* TO '${WP_USER}'@'%';

FLUSH PRIVILEGES;